// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Summon Software Labs.

#include <algorithm>
#include <array>
#include <utility>
#include <vector>

#include "analysis.hpp"
#include "dccp/cooling_observatory/checked.hpp"

namespace dccp::cooling_observatory {
namespace {

constexpr std::array<std::pair<ReserveBasis, std::string_view>, 4> kBases{{
    {ReserveBasis::Unknown, "unknown"},
    {ReserveBasis::Claimed, "claimed"},
    {ReserveBasis::Evidenced, "evidenced"},
    {ReserveBasis::Mixed, "mixed"},
}};

constexpr std::array<std::pair<ReserveContributionKind, std::string_view>, 4> kContributionKinds{{
    {ReserveContributionKind::DeclaredClaim, "declared_claim"},
    {ReserveContributionKind::MeasuredHeadroom, "measured_headroom"},
    {ReserveContributionKind::StandbyElement, "standby_element"},
    {ReserveContributionKind::RecoveredEstimate, "recovered_estimate"},
}};

}  // namespace

std::string_view to_token(ReserveBasis basis) noexcept {
  for (const auto& entry : kBases) {
    if (entry.first == basis) {
      return entry.second;
    }
  }
  return "unknown";
}

std::optional<ReserveBasis> parse_reserve_basis(std::string_view token) noexcept {
  for (const auto& entry : kBases) {
    if (entry.second == token) {
      return entry.first;
    }
  }
  return std::nullopt;
}

std::string_view to_token(ReserveContributionKind kind) noexcept {
  for (const auto& entry : kContributionKinds) {
    if (entry.first == kind) {
      return entry.second;
    }
  }
  return "unknown";
}

std::optional<ReserveContributionKind> parse_reserve_contribution_kind(std::string_view token) noexcept {
  for (const auto& entry : kContributionKinds) {
    if (entry.second == token) {
      return entry.first;
    }
  }
  return std::nullopt;
}

namespace {

/// What one element could contribute, and why it might not.
struct CapabilityEntry {
  SubjectRef element{};
  std::optional<std::int64_t> derated_capacity{};
  Freshness capability_freshness = Freshness::Unknown;
  LifecycleState condition = LifecycleState::Unknown;
  Freshness condition_freshness = Freshness::Unknown;
  bool delivering = false;
  std::vector<EvidenceRef> evidence{};
  std::vector<Indeterminacy> indeterminacies{};
};

/// The derived subject that carries measured delivery attributed to a loop. A
/// derived identity is internal and generated by the library, so it can never
/// collide with a producer's measurement identity.
SubjectRef loop_delivered_subject(const LoopId& loop) {
  return derived_subject("loop." + loop.str() + ".delivered");
}

std::vector<CapabilityEntry> capability_pool(const AnalysisContext& context) {
  std::vector<CapabilityEntry> out;
  const PlantModel& structure = context.structure();
  for (const PlantComponent& component : structure.components()) {
    if (component.kind == ComponentKind::RackGroup || component.kind == ComponentKind::Reservoir) {
      continue;
    }
    CapabilityEntry entry;
    entry.element = component.subject();

    for (const Observation& observation : context.evidence_for(entry.element)) {
      const Freshness classified = classify(observation, context.state().freshness_policy, context.now_ms,
                                            context.state().epoch, context.state().generation);
      entry.evidence.push_back(make_reference(observation, context.state().revision, 0));
      if (observation.kind == ObservationKind::Capability) {
        if (!is_current(classified)) {
          // A declaration that cannot be used as current evidence does not
          // describe the capability that was summed, so it does not drag the
          // figure's freshness down; it is reported as the reason no capability
          // was found at all.
          entry.capability_freshness = worst(entry.capability_freshness, classified);
          continue;
        }
        if (observation.capability_dimension != Dimension::Flow) {
          Indeterminacy indeterminacy;
          indeterminacy.code = Code::UnsupportedValue;
          indeterminacy.reason = "capability_not_a_flow";
          indeterminacy.detail = "capability declared in " +
                                 std::string(to_token(observation.capability_dimension)) +
                                 " is not a flow and cannot be summed into flow reserve";
          entry.indeterminacies.push_back(std::move(indeterminacy));
          continue;
        }
        const std::optional<std::int64_t> derated =
            checked_mul_div_round(observation.declared_capacity, 1000000 - observation.derate_ppm,
                                  1000000);
        if (!derated.has_value()) {
          Indeterminacy indeterminacy;
          indeterminacy.code = Code::LimitExceeded;
          indeterminacy.reason = "capability_out_of_range";
          indeterminacy.detail = "the derated capability does not fit a signed 64-bit value";
          entry.indeterminacies.push_back(std::move(indeterminacy));
          continue;
        }
        if (!entry.derated_capacity.has_value()) {
          entry.derated_capacity = derated.value();
          // The capability that was accepted is current evidence, whatever an
          // older declaration for the same element said.
          entry.capability_freshness = Freshness::Fresh;
        } else {
          const std::optional<std::int64_t> total =
              checked_add(entry.derated_capacity.value(), derated.value());
          if (total.has_value()) {
            entry.derated_capacity = total.value();
          }
        }
      } else if (observation.kind == ObservationKind::EquipmentState) {
        entry.condition_freshness = worst(entry.condition_freshness, classified);
        entry.condition = observation.state;
      }
    }
    out.push_back(std::move(entry));
  }
  return out;
}

std::vector<const CapabilityEntry*> entries_in_loop(const std::vector<CapabilityEntry>& pool,
                                                    const PlantModel& structure, const LoopId& loop) {
  std::vector<const CapabilityEntry*> out;
  for (const CapabilityEntry& entry : pool) {
    if (entry.element.kind == SubjectKind::Loop) {
      if (entry.element.id.view() == loop.view()) {
        out.push_back(&entry);
      }
      continue;
    }
    const std::optional<PlantComponent> component = structure.component(entry.element.kind, entry.element.id);
    if (component.has_value() && component.value().loop == loop) {
      out.push_back(&entry);
    }
  }
  return out;
}

std::vector<const CapabilityEntry*> entries_in_plant(const std::vector<CapabilityEntry>& pool,
                                                     const PlantModel& structure, PlantId plant_id) {
  std::vector<const CapabilityEntry*> out;
  const std::optional<CoolingPlant> plant = structure.plant(plant_id);
  if (!plant.has_value()) {
    return out;
  }
  for (const CapabilityEntry& entry : pool) {
    if (entry.element.kind != SubjectKind::Loop) {
      continue;
    }
    const std::optional<Loop> loop = structure.loop(rebind<LoopId>(entry.element.id));
    if (loop.has_value() && loop.value().plant == plant_id) {
      out.push_back(&entry);
    }
  }
  return out;
}

ReserveObservation observe_scope(const AnalysisContext& context, const SubjectRef& scope,
                                 const std::vector<const CapabilityEntry*>& entries,
                                 const Maybe<Quantity>& delivered,
                                 const std::vector<DeliveryObservation>& observations,
                                 const std::vector<DeliveryPoint>& points, const QueryFilter& filter) {
  (void)observations;
  (void)points;
  (void)filter;
  ReserveObservation out;
  out.scope = scope;
  out.dimension = Dimension::Flow;

  // The capability pool: derated declared capacity of elements whose condition
  // currently allows delivery.
  std::int64_t capable_total = 0;
  bool capable_overflow = false;
  bool have_capability = false;
  std::vector<Freshness> capable_freshness;
  for (const CapabilityEntry* entry : entries) {
    for (const Indeterminacy& indeterminacy : entry->indeterminacies) {
      out.indeterminacies.push_back(indeterminacy);
    }
    if (!entry->derated_capacity.has_value()) {
      continue;
    }
    if (!is_current(entry->capability_freshness)) {
      capable_freshness.push_back(entry->capability_freshness);
      continue;
    }
    const bool can_run = may_deliver(entry->condition);
    if (!can_run) {
      // An element that cannot deliver contributes nothing, and the reason is
      // recorded as a contribution rather than as silence.
      ReserveContribution contribution;
      contribution.kind = ReserveContributionKind::StandbyElement;
      contribution.element = entry->element;
      contribution.amount = Quantity(Dimension::Flow, 0);
      contribution.freshness = entry->condition_freshness;
      contribution.evidence = entry->evidence;
      out.contributions.push_back(std::move(contribution));
      continue;
    }
    const std::optional<std::int64_t> total = checked_add(capable_total, entry->derated_capacity.value());
    if (!total.has_value()) {
      capable_overflow = true;
      break;
    }
    capable_total = total.value();
    have_capability = true;
    capable_freshness.push_back(entry->capability_freshness);

    ReserveContribution contribution;
    contribution.kind = ReserveContributionKind::StandbyElement;
    contribution.element = entry->element;
    contribution.amount = Quantity(Dimension::Flow, entry->derated_capacity.value());
    contribution.freshness = entry->capability_freshness;
    contribution.evidence = entry->evidence;
    out.contributions.push_back(std::move(contribution));
  }

  if (capable_overflow) {
    Indeterminacy indeterminacy;
    indeterminacy.code = Code::LimitExceeded;
    indeterminacy.reason = "capability_sum_out_of_range";
    indeterminacy.detail = "the summed capability of this scope does not fit a signed 64-bit flow";
    out.indeterminacies.push_back(std::move(indeterminacy));
  } else if (have_capability) {
    out.capability.value = Maybe<Quantity>::of(Quantity(Dimension::Flow, capable_total));
    out.capability.freshness = fold_worst_of(capable_freshness);
  } else if (!capable_freshness.empty()) {
    // Declarations exist for this scope and none of them is current. No value is
    // reported: a capability of zero would claim the equipment can deliver
    // nothing, which is not what was observed.
    out.capability.freshness = fold_worst_of(capable_freshness);
    Indeterminacy indeterminacy;
    indeterminacy.code = Code::StaleEvidence;
    indeterminacy.reason = "capability_not_current";
    indeterminacy.detail =
        "no current capability declaration covers this scope, so no capability figure is reported";
    out.indeterminacies.push_back(std::move(indeterminacy));
  }

  // Measured delivery at this scope.
  out.delivered.value = delivered;
  if (delivered.has_value()) {
    out.delivered.freshness = Freshness::Fresh;
  }

  // Evidenced reserve: capability minus what is already being delivered. Both
  // inputs must be current, because a headroom computed from a stale delivery
  // is a headroom against a plant that no longer exists.
  if (out.capability.value.has_value() && is_current(out.capability.freshness) &&
      out.delivered.value.has_value() && is_current(out.delivered.freshness)) {
    const std::optional<std::int64_t> headroom =
        checked_sub(out.capability.value.value().value, out.delivered.value.value().value);
    if (headroom.has_value()) {
      out.evidenced.value = Maybe<Quantity>::of(Quantity(Dimension::Flow, headroom.value()));
      out.evidenced.freshness = Freshness::Fresh;
      ReserveContribution contribution;
      contribution.kind = ReserveContributionKind::MeasuredHeadroom;
      contribution.amount = Quantity(Dimension::Flow, headroom.value());
      contribution.freshness = Freshness::Fresh;
      out.contributions.push_back(std::move(contribution));
    } else {
      Indeterminacy indeterminacy;
      indeterminacy.code = Code::LimitExceeded;
      indeterminacy.reason = "headroom_out_of_range";
      indeterminacy.detail = "the computed headroom does not fit a signed 64-bit flow";
      out.indeterminacies.push_back(std::move(indeterminacy));
    }
  } else if (!entries.empty()) {
    Indeterminacy indeterminacy;
    indeterminacy.code = out.delivered.value.has_value() ? Code::StaleEvidence : Code::MissingEvidence;
    indeterminacy.reason =
        out.capability.value.has_value() ? "delivery_not_current" : "capability_not_current";
    indeterminacy.detail =
        "evidenced reserve needs a current capability and a current delivery at the same scope";
    out.indeterminacies.push_back(std::move(indeterminacy));
  }

  // Claimed reserve: declarations whose evidence is current, minus the claims
  // that rest on assumptions this runtime could check and found false.
  std::int64_t claimed_total = 0;
  bool have_claim = false;
  bool claim_overflow = false;
  std::vector<Freshness> claim_freshness;
  for (const Observation& observation : context.evidence_of_kind(ObservationKind::ReserveClaim)) {
    if (observation.subject.kind != scope.kind || observation.subject.id != scope.id) {
      continue;
    }
    const Freshness classified = classify(observation, context.state().freshness_policy, context.now_ms,
                                          context.state().epoch, context.state().generation);
    ReserveContribution contribution;
    contribution.kind = ReserveContributionKind::DeclaredClaim;
    contribution.claim_id = observation.subject.id;
    contribution.amount = observation.declared_reserve;
    contribution.freshness = classified;
    contribution.evidence.push_back(make_reference(observation, context.state().revision, 0));
    for (const StrongId& assumption : observation.assumes_available) {
      const SubjectRef assumed(SubjectKind::Pump, assumption);
      const bool present = context.structure().knows(assumed) ||
                           context.structure().knows(SubjectRef(SubjectKind::Cdu, assumption)) ||
                           context.structure().knows(SubjectRef(SubjectKind::Chiller, assumption)) ||
                           context.structure().knows(SubjectRef(SubjectKind::Crah, assumption));
      if (!present) {
        // The claim assumes an element the adopted structure does not contain.
        // The claim is recorded, and the assumption it rests on is named, so a
        // consumer can reject the figure without re-deriving the structure.
        contribution.unverified_assumptions.push_back(assumption);
      }
    }
    if (classified == Freshness::Recovered) {
      contribution.kind = ReserveContributionKind::RecoveredEstimate;
    }
    if (is_current(classified) && observation.declared_reserve.dimension == Dimension::Flow &&
        contribution.refuted_assumptions.empty()) {
      const std::optional<std::int64_t> total = checked_add(claimed_total, observation.declared_reserve.value);
      if (!total.has_value()) {
        claim_overflow = true;
      } else {
        claimed_total = total.value();
        have_claim = true;
        claim_freshness.push_back(classified);
      }
    }
    out.contributions.push_back(std::move(contribution));
  }

  if (have_claim && !claim_overflow) {
    out.claimed.value = Maybe<Quantity>::of(Quantity(Dimension::Flow, claimed_total));
    out.claimed.freshness = fold_worst_of(claim_freshness);
  }
  if (claim_overflow) {
    Indeterminacy indeterminacy;
    indeterminacy.code = Code::LimitExceeded;
    indeterminacy.reason = "claimed_reserve_out_of_range";
    indeterminacy.detail = "the summed claimed reserve does not fit a signed 64-bit flow";
    out.indeterminacies.push_back(std::move(indeterminacy));
  }

  // The binding figure, and what it rests on.
  const bool have_evidenced = out.evidenced.value.has_value() && is_current(out.evidenced.freshness);
  const bool have_claimed = out.claimed.value.has_value() && is_current(out.claimed.freshness);
  if (have_evidenced && have_claimed) {
    out.basis = ReserveBasis::Mixed;
    const std::int64_t smaller = std::min(out.evidenced.value.value().value, out.claimed.value.value().value);
    out.binding.value = Maybe<Quantity>::of(Quantity(Dimension::Flow, smaller));
    out.binding.freshness = Freshness::Fresh;
  } else if (have_evidenced) {
    out.basis = ReserveBasis::Evidenced;
    out.binding = out.evidenced;
  } else if (have_claimed) {
    out.basis = ReserveBasis::Claimed;
    out.binding = out.claimed;
  } else {
    out.basis = ReserveBasis::Unknown;
  }

  std::vector<Freshness> parts{out.claimed.freshness, out.evidenced.freshness, out.capability.freshness,
                               out.delivered.freshness};
  out.freshness = fold_worst_of(parts);
  return out;
}

}  // namespace

ReserveReport analyse_reserve(const AnalysisContext& context, const QueryFilter& filter) {
  ReserveReport out;
  out.generation = context.state().generation;
  out.epoch = context.state().epoch;
  out.revision = context.state().revision;
  out.as_of_ms = context.now_ms;
  out.dimension = Dimension::Flow;

  const std::vector<DeliveryPoint> points = delivery_points(context);
  std::vector<DeliveryObservation> observations;
  observations.reserve(points.size());
  for (const DeliveryPoint& point : points) {
    observations.push_back(observe_delivery_point(context, point, filter));
  }

  const std::vector<CapabilityEntry> pool = capability_pool(context);

  // Measured delivery attributed to one loop: the sum of the flows of the
  // points that depend on it. A point without a current flow contributes
  // nothing to the sum and marks the sum as not fully evidenced.
  struct Sum {
    std::int64_t total = 0;
    bool any = false;
    bool overflow = false;
    std::vector<Freshness> freshness;
  };

  for (const Loop& loop : context.structure().loops()) {
    if (filter.loop.has_value() && loop.id != filter.loop.value()) {
      continue;
    }
    const SubjectRef scope(SubjectKind::Loop, rebind<StrongId>(loop.id));
    const std::vector<StrongId> served = points_served_by(context, scope, points);
    Sum sum;
    for (std::size_t i = 0; i < points.size(); ++i) {
      if (std::find(served.begin(), served.end(), points[i].id) == served.end()) {
        continue;
      }
      if (!observations[i].flow.value.has_value()) {
        continue;
      }
      const std::optional<std::int64_t> next =
          checked_add(sum.total, observations[i].flow.value.value().value);
      if (!next.has_value()) {
        sum.overflow = true;
        break;
      }
      sum.total = next.value();
      sum.any = true;
      sum.freshness.push_back(observations[i].flow.freshness);
    }

    Maybe<Quantity> delivered;
    Freshness delivered_freshness = Freshness::Unknown;
    if (sum.any && !sum.overflow) {
      delivered = Maybe<Quantity>::of(Quantity(Dimension::Flow, sum.total));
      delivered_freshness = fold_worst_of(sum.freshness);
    }

    const std::vector<const CapabilityEntry*> entries =
        entries_in_loop(pool, context.structure(), loop.id);
    ReserveObservation observation =
        observe_scope(context, scope, entries, delivered, observations, points, filter);
    if (delivered.has_value()) {
      observation.delivered.freshness = delivered_freshness;
    }
    if (sum.overflow) {
      Indeterminacy indeterminacy;
      indeterminacy.code = Code::LimitExceeded;
      indeterminacy.reason = "loop_delivery_out_of_range";
      indeterminacy.detail = "the summed measured delivery of this loop does not fit a signed 64-bit flow";
      observation.indeterminacies.push_back(std::move(indeterminacy));
    }
    if (filter.require_evidenced && observation.basis != ReserveBasis::Evidenced &&
        observation.basis != ReserveBasis::Mixed) {
      continue;
    }
    out.scopes.push_back(std::move(observation));
  }

  // A plant-scope figure, when a plant was named: it is the sum over the loops
  // the plant contains, and it is reported separately from the loops so that a
  // consumer never has to add scope figures together itself.
  if (filter.plant.has_value()) {
    const SubjectRef scope(SubjectKind::Plant, rebind<StrongId>(filter.plant.value()));
    std::vector<const CapabilityEntry*> entries;
    for (const Loop& loop : context.structure().loops()) {
      if (loop.plant != filter.plant.value()) {
        continue;
      }
      const std::vector<const CapabilityEntry*> in_loop = entries_in_loop(pool, context.structure(), loop.id);
      entries.insert(entries.end(), in_loop.begin(), in_loop.end());
    }
    Sum sum;
    for (std::size_t i = 0; i < points.size(); ++i) {
      if (!observations[i].flow.value.has_value()) {
        continue;
      }
      const std::optional<std::int64_t> next = checked_add(sum.total, observations[i].flow.value.value().value);
      if (!next.has_value()) {
        sum.overflow = true;
        break;
      }
      sum.total = next.value();
      sum.any = true;
      sum.freshness.push_back(observations[i].flow.freshness);
    }
    Maybe<Quantity> delivered;
    if (sum.any && !sum.overflow) {
      delivered = Maybe<Quantity>::of(Quantity(Dimension::Flow, sum.total));
    }
    ReserveObservation observation =
        observe_scope(context, scope, entries, delivered, observations, points, filter);
    if (delivered.has_value()) {
      observation.delivered.freshness = fold_worst_of(sum.freshness);
    }
    if (!filter.require_evidenced || observation.basis == ReserveBasis::Evidenced ||
        observation.basis == ReserveBasis::Mixed) {
      out.scopes.push_back(std::move(observation));
    }
  } else if (!filter.loop.has_value()) {
    for (const ThermalZone& zone : context.structure().zones()) {
      if (filter.zone.has_value() && zone.id != filter.zone.value()) {
        continue;
      }
      const SubjectRef scope(SubjectKind::Zone, rebind<StrongId>(zone.id));
      Maybe<Quantity> delivered;
      for (std::size_t i = 0; i < points.size(); ++i) {
        if (points[i].zone == zone.id && observations[i].flow.value.has_value()) {
          delivered = observations[i].flow.value;
          break;
        }
      }
      ReserveObservation observation =
          observe_scope(context, scope, {}, delivered, observations, points, filter);
      if (filter.require_evidenced && observation.basis != ReserveBasis::Evidenced &&
          observation.basis != ReserveBasis::Mixed) {
        continue;
      }
      out.scopes.push_back(std::move(observation));
    }
  }

  std::sort(out.scopes.begin(), out.scopes.end(),
            [](const ReserveObservation& a, const ReserveObservation& b) { return a.scope < b.scope; });

  std::vector<Freshness> parts;
  for (const ReserveObservation& observation : out.scopes) {
    parts.push_back(observation.freshness);
  }
  out.freshness = parts.empty() ? Freshness::Unknown : fold_worst_of(parts);
  return out;
}

}  // namespace dccp::cooling_observatory